version: "3.7"

services:
    # image project
    app:
        container_name: christiansteffens-laravel-9
        build:
            context: .
            dockerfile: Dockerfile
        image: christiansteffens/laravel9-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks: 
            - laravel-9
    
    # nginx
    nginx:
        container_name: christiansteffens-nginx
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - "8990:80"
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - laravel-9

networks: 
    laravel-9:
        driver: bridge